- name: Get client pubkey
  ansible.builtin.command:
    cmd: wg pubkey
    stdin: "{{ wireguard_client_privkey }}"
  changed_when: false
  register: result

- name: Store client pubkey in var
  ansible.builtin.set_fact:
    wireguard_client_pubkey: "{{ result.stdout }}"

- name: Add peer to config
  become: true
  notify: Restart wireguard
  ansible.builtin.blockinfile:
    path: "/etc/wireguard/{{ wireguard_config }}"
    marker_begin: "device {{ wireguard_peer_name | default(wireguard_client_pubkey | hash('md5')) }}"
    marker_end: "end"
    marker: "# {mark}"
