- name: Install required pkgs
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - ca-certificates
      - curl

- name: Setup keyrings
  become: true
  ansible.builtin.command: install -m 0755 -d /etc/apt/keyrings
  changed_when: false

- name: Get docker keyring
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Add docker repo
  become: true
  ansible.builtin.shell:
    cmd: >
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc]
      https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable"
      > /etc/apt/sources.list.d/docker.list
    creates: /etc/apt/sources.list.d/docker.list

- name: Install docker and addons
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
