- name: Install requirements
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - rclone
      - swaks
      - cron

- name: Tell to setup rclone by hand
  ansible.builtin.pause:
    prompt: "/!\\ Setup rclone by hand!"

- name: Create cron job for rclone
  become: true
  ansible.builtin.cron:
    user: root
    hour: "6"
    minute: "2"
    cron_file: rclone-backups
    name: push all backups to remote
    job: "/usr/bin/rclone sync /backups {{ backups_rclone_remote }}:{{ backups_rclone_dir }}"

- name: Add mailjet creds
  become: true
  block:
    - name: Create secrets dir
      ansible.builtin.file:
        path: /root/.secrets
        state: directory
        mode: "0700"
        owner: root
        group: root
    - name: Store mailjet secrets
      ansible.builtin.template:
        src: mailjet.ini.j2
        dest: /root/.secrets/mailjet.ini
        mode: "0400"
        owner: root
        group: root

- name: Add mail backup script to cron weekly
  become: true
  ansible.builtin.template:
    src: mail-backup.sh.j2
    dest: /etc/cron.weekly/mail-backup
    mode: "0744"
    owner: root
    group: root
